#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barbari_DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Barbari_Db")]
	public partial class DataClassBarbariDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBarErsali_Tbl(BarErsali_Tbl instance);
    partial void UpdateBarErsali_Tbl(BarErsali_Tbl instance);
    partial void DeleteBarErsali_Tbl(BarErsali_Tbl instance);
    partial void InsertKalaDaryafti_Tbl(KalaDaryafti_Tbl instance);
    partial void UpdateKalaDaryafti_Tbl(KalaDaryafti_Tbl instance);
    partial void DeleteKalaDaryafti_Tbl(KalaDaryafti_Tbl instance);
    partial void InsertRanande_Tbl(Ranande_Tbl instance);
    partial void UpdateRanande_Tbl(Ranande_Tbl instance);
    partial void DeleteRanande_Tbl(Ranande_Tbl instance);
    partial void InsertUsers_Tbl(Users_Tbl instance);
    partial void UpdateUsers_Tbl(Users_Tbl instance);
    partial void DeleteUsers_Tbl(Users_Tbl instance);
    partial void InsertCity_Tbl(City_Tbl instance);
    partial void UpdateCity_Tbl(City_Tbl instance);
    partial void DeleteCity_Tbl(City_Tbl instance);
    partial void InsertCustomers_Tbl(Customers_Tbl instance);
    partial void UpdateCustomers_Tbl(Customers_Tbl instance);
    partial void DeleteCustomers_Tbl(Customers_Tbl instance);
    #endregion
		
		public DataClassBarbariDataContext() : 
				base(global::Barbari_DAL.Properties.Settings.Default.Barbari_DbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassBarbariDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassBarbariDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassBarbariDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassBarbariDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BarErsali_Tbl> BarErsali_Tbls
		{
			get
			{
				return this.GetTable<BarErsali_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<KalaDaryafti_Tbl> KalaDaryafti_Tbls
		{
			get
			{
				return this.GetTable<KalaDaryafti_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Ranande_Tbl> Ranande_Tbls
		{
			get
			{
				return this.GetTable<Ranande_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Users_Tbl> Users_Tbls
		{
			get
			{
				return this.GetTable<Users_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<City_Tbl> City_Tbls
		{
			get
			{
				return this.GetTable<City_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Customers_Tbl> Customers_Tbls
		{
			get
			{
				return this.GetTable<Customers_Tbl>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BarErsali_Tbl")]
	public partial class BarErsali_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _BarErsaliBarname;
		
		private string _BarErsaliCodeFerestande;
		
		private string _BarErsaliNamFerestande;
		
		private string _BarErsaliFamilyFerestande;
		
		private string _BarErsaliMobileFerestande;
		
		private string _BarErsaliNamGerande;
		
		private string _BarErsaliFamilyGerande;
		
		private string _BarErsaliMobileGerande;
		
		private string _BarErsaliShahreMabda;
		
		private string _BarErsaliAnbarMabda;
		
		private string _BarErsaliShahreMaghsad1;
		
		private string _BarErsaliAnbarMaghsad1;
		
		private string _BarErsaliShahreMaghsad2;
		
		private string _BarErsaliAnbarMaghsad2;
		
		private string _BarErsaliTarikh;
		
		private string _BarErsaliSaat;
		
		private string _BarErsaliCodeRanande;
		
		private string _BarErsaliNamRanande;
		
		private string _BarErsaliFamilyRanande;
		
		private string _BarErsaliMobileRanande;
		
		private System.Nullable<decimal> _BarErsaliKerayeRanande;
		
		private decimal _BarErsaliPishKeraye;
		
		private decimal _BarErsaliPasKeraye;
		
		private System.Nullable<decimal> _BarErsaliBime;
		
		private System.Nullable<decimal> _BarErsaliAnbardari;
		
		private System.Nullable<decimal> _BarErsaliShahri;
		
		private System.Nullable<decimal> _BarErsaliBastebandi;
		
		private string _BarErsaliUserNameKarmand;
		
		private EntitySet<KalaDaryafti_Tbl> _KalaDaryafti_Tbls;
		
		private EntityRef<Ranande_Tbl> _Ranande_Tbl;
		
		private EntityRef<Users_Tbl> _Users_Tbl;
		
		private EntityRef<Customers_Tbl> _Customers_Tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBarErsaliBarnameChanging(string value);
    partial void OnBarErsaliBarnameChanged();
    partial void OnBarErsaliCodeFerestandeChanging(string value);
    partial void OnBarErsaliCodeFerestandeChanged();
    partial void OnBarErsaliNamFerestandeChanging(string value);
    partial void OnBarErsaliNamFerestandeChanged();
    partial void OnBarErsaliFamilyFerestandeChanging(string value);
    partial void OnBarErsaliFamilyFerestandeChanged();
    partial void OnBarErsaliMobileFerestandeChanging(string value);
    partial void OnBarErsaliMobileFerestandeChanged();
    partial void OnBarErsaliNamGerandeChanging(string value);
    partial void OnBarErsaliNamGerandeChanged();
    partial void OnBarErsaliFamilyGerandeChanging(string value);
    partial void OnBarErsaliFamilyGerandeChanged();
    partial void OnBarErsaliMobileGerandeChanging(string value);
    partial void OnBarErsaliMobileGerandeChanged();
    partial void OnBarErsaliShahreMabdaChanging(string value);
    partial void OnBarErsaliShahreMabdaChanged();
    partial void OnBarErsaliAnbarMabdaChanging(string value);
    partial void OnBarErsaliAnbarMabdaChanged();
    partial void OnBarErsaliShahreMaghsad1Changing(string value);
    partial void OnBarErsaliShahreMaghsad1Changed();
    partial void OnBarErsaliAnbarMaghsad1Changing(string value);
    partial void OnBarErsaliAnbarMaghsad1Changed();
    partial void OnBarErsaliShahreMaghsad2Changing(string value);
    partial void OnBarErsaliShahreMaghsad2Changed();
    partial void OnBarErsaliAnbarMaghsad2Changing(string value);
    partial void OnBarErsaliAnbarMaghsad2Changed();
    partial void OnBarErsaliTarikhChanging(string value);
    partial void OnBarErsaliTarikhChanged();
    partial void OnBarErsaliSaatChanging(string value);
    partial void OnBarErsaliSaatChanged();
    partial void OnBarErsaliCodeRanandeChanging(string value);
    partial void OnBarErsaliCodeRanandeChanged();
    partial void OnBarErsaliNamRanandeChanging(string value);
    partial void OnBarErsaliNamRanandeChanged();
    partial void OnBarErsaliFamilyRanandeChanging(string value);
    partial void OnBarErsaliFamilyRanandeChanged();
    partial void OnBarErsaliMobileRanandeChanging(string value);
    partial void OnBarErsaliMobileRanandeChanged();
    partial void OnBarErsaliKerayeRanandeChanging(System.Nullable<decimal> value);
    partial void OnBarErsaliKerayeRanandeChanged();
    partial void OnBarErsaliPishKerayeChanging(decimal value);
    partial void OnBarErsaliPishKerayeChanged();
    partial void OnBarErsaliPasKerayeChanging(decimal value);
    partial void OnBarErsaliPasKerayeChanged();
    partial void OnBarErsaliBimeChanging(System.Nullable<decimal> value);
    partial void OnBarErsaliBimeChanged();
    partial void OnBarErsaliAnbardariChanging(System.Nullable<decimal> value);
    partial void OnBarErsaliAnbardariChanged();
    partial void OnBarErsaliShahriChanging(System.Nullable<decimal> value);
    partial void OnBarErsaliShahriChanged();
    partial void OnBarErsaliBastebandiChanging(System.Nullable<decimal> value);
    partial void OnBarErsaliBastebandiChanged();
    partial void OnBarErsaliUserNameKarmandChanging(string value);
    partial void OnBarErsaliUserNameKarmandChanged();
    #endregion
		
		public BarErsali_Tbl()
		{
			this._KalaDaryafti_Tbls = new EntitySet<KalaDaryafti_Tbl>(new Action<KalaDaryafti_Tbl>(this.attach_KalaDaryafti_Tbls), new Action<KalaDaryafti_Tbl>(this.detach_KalaDaryafti_Tbls));
			this._Ranande_Tbl = default(EntityRef<Ranande_Tbl>);
			this._Users_Tbl = default(EntityRef<Users_Tbl>);
			this._Customers_Tbl = default(EntityRef<Customers_Tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliBarname", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string BarErsaliBarname
		{
			get
			{
				return this._BarErsaliBarname;
			}
			set
			{
				if ((this._BarErsaliBarname != value))
				{
					this.OnBarErsaliBarnameChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliBarname = value;
					this.SendPropertyChanged("BarErsaliBarname");
					this.OnBarErsaliBarnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliCodeFerestande", DbType="VarChar(12)")]
		public string BarErsaliCodeFerestande
		{
			get
			{
				return this._BarErsaliCodeFerestande;
			}
			set
			{
				if ((this._BarErsaliCodeFerestande != value))
				{
					if (this._Customers_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBarErsaliCodeFerestandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliCodeFerestande = value;
					this.SendPropertyChanged("BarErsaliCodeFerestande");
					this.OnBarErsaliCodeFerestandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliNamFerestande", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string BarErsaliNamFerestande
		{
			get
			{
				return this._BarErsaliNamFerestande;
			}
			set
			{
				if ((this._BarErsaliNamFerestande != value))
				{
					this.OnBarErsaliNamFerestandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliNamFerestande = value;
					this.SendPropertyChanged("BarErsaliNamFerestande");
					this.OnBarErsaliNamFerestandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliFamilyFerestande", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string BarErsaliFamilyFerestande
		{
			get
			{
				return this._BarErsaliFamilyFerestande;
			}
			set
			{
				if ((this._BarErsaliFamilyFerestande != value))
				{
					this.OnBarErsaliFamilyFerestandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliFamilyFerestande = value;
					this.SendPropertyChanged("BarErsaliFamilyFerestande");
					this.OnBarErsaliFamilyFerestandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliMobileFerestande", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string BarErsaliMobileFerestande
		{
			get
			{
				return this._BarErsaliMobileFerestande;
			}
			set
			{
				if ((this._BarErsaliMobileFerestande != value))
				{
					this.OnBarErsaliMobileFerestandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliMobileFerestande = value;
					this.SendPropertyChanged("BarErsaliMobileFerestande");
					this.OnBarErsaliMobileFerestandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliNamGerande", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string BarErsaliNamGerande
		{
			get
			{
				return this._BarErsaliNamGerande;
			}
			set
			{
				if ((this._BarErsaliNamGerande != value))
				{
					this.OnBarErsaliNamGerandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliNamGerande = value;
					this.SendPropertyChanged("BarErsaliNamGerande");
					this.OnBarErsaliNamGerandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliFamilyGerande", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string BarErsaliFamilyGerande
		{
			get
			{
				return this._BarErsaliFamilyGerande;
			}
			set
			{
				if ((this._BarErsaliFamilyGerande != value))
				{
					this.OnBarErsaliFamilyGerandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliFamilyGerande = value;
					this.SendPropertyChanged("BarErsaliFamilyGerande");
					this.OnBarErsaliFamilyGerandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliMobileGerande", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string BarErsaliMobileGerande
		{
			get
			{
				return this._BarErsaliMobileGerande;
			}
			set
			{
				if ((this._BarErsaliMobileGerande != value))
				{
					this.OnBarErsaliMobileGerandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliMobileGerande = value;
					this.SendPropertyChanged("BarErsaliMobileGerande");
					this.OnBarErsaliMobileGerandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliShahreMabda", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BarErsaliShahreMabda
		{
			get
			{
				return this._BarErsaliShahreMabda;
			}
			set
			{
				if ((this._BarErsaliShahreMabda != value))
				{
					this.OnBarErsaliShahreMabdaChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliShahreMabda = value;
					this.SendPropertyChanged("BarErsaliShahreMabda");
					this.OnBarErsaliShahreMabdaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliAnbarMabda", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BarErsaliAnbarMabda
		{
			get
			{
				return this._BarErsaliAnbarMabda;
			}
			set
			{
				if ((this._BarErsaliAnbarMabda != value))
				{
					this.OnBarErsaliAnbarMabdaChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliAnbarMabda = value;
					this.SendPropertyChanged("BarErsaliAnbarMabda");
					this.OnBarErsaliAnbarMabdaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliShahreMaghsad1", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BarErsaliShahreMaghsad1
		{
			get
			{
				return this._BarErsaliShahreMaghsad1;
			}
			set
			{
				if ((this._BarErsaliShahreMaghsad1 != value))
				{
					this.OnBarErsaliShahreMaghsad1Changing(value);
					this.SendPropertyChanging();
					this._BarErsaliShahreMaghsad1 = value;
					this.SendPropertyChanged("BarErsaliShahreMaghsad1");
					this.OnBarErsaliShahreMaghsad1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliAnbarMaghsad1", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BarErsaliAnbarMaghsad1
		{
			get
			{
				return this._BarErsaliAnbarMaghsad1;
			}
			set
			{
				if ((this._BarErsaliAnbarMaghsad1 != value))
				{
					this.OnBarErsaliAnbarMaghsad1Changing(value);
					this.SendPropertyChanging();
					this._BarErsaliAnbarMaghsad1 = value;
					this.SendPropertyChanged("BarErsaliAnbarMaghsad1");
					this.OnBarErsaliAnbarMaghsad1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliShahreMaghsad2", DbType="NVarChar(100)")]
		public string BarErsaliShahreMaghsad2
		{
			get
			{
				return this._BarErsaliShahreMaghsad2;
			}
			set
			{
				if ((this._BarErsaliShahreMaghsad2 != value))
				{
					this.OnBarErsaliShahreMaghsad2Changing(value);
					this.SendPropertyChanging();
					this._BarErsaliShahreMaghsad2 = value;
					this.SendPropertyChanged("BarErsaliShahreMaghsad2");
					this.OnBarErsaliShahreMaghsad2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliAnbarMaghsad2", DbType="NVarChar(100)")]
		public string BarErsaliAnbarMaghsad2
		{
			get
			{
				return this._BarErsaliAnbarMaghsad2;
			}
			set
			{
				if ((this._BarErsaliAnbarMaghsad2 != value))
				{
					this.OnBarErsaliAnbarMaghsad2Changing(value);
					this.SendPropertyChanging();
					this._BarErsaliAnbarMaghsad2 = value;
					this.SendPropertyChanged("BarErsaliAnbarMaghsad2");
					this.OnBarErsaliAnbarMaghsad2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliTarikh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string BarErsaliTarikh
		{
			get
			{
				return this._BarErsaliTarikh;
			}
			set
			{
				if ((this._BarErsaliTarikh != value))
				{
					this.OnBarErsaliTarikhChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliTarikh = value;
					this.SendPropertyChanged("BarErsaliTarikh");
					this.OnBarErsaliTarikhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliSaat", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string BarErsaliSaat
		{
			get
			{
				return this._BarErsaliSaat;
			}
			set
			{
				if ((this._BarErsaliSaat != value))
				{
					this.OnBarErsaliSaatChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliSaat = value;
					this.SendPropertyChanged("BarErsaliSaat");
					this.OnBarErsaliSaatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliCodeRanande", DbType="VarChar(12)")]
		public string BarErsaliCodeRanande
		{
			get
			{
				return this._BarErsaliCodeRanande;
			}
			set
			{
				if ((this._BarErsaliCodeRanande != value))
				{
					if (this._Ranande_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBarErsaliCodeRanandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliCodeRanande = value;
					this.SendPropertyChanged("BarErsaliCodeRanande");
					this.OnBarErsaliCodeRanandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliNamRanande", DbType="NVarChar(150)")]
		public string BarErsaliNamRanande
		{
			get
			{
				return this._BarErsaliNamRanande;
			}
			set
			{
				if ((this._BarErsaliNamRanande != value))
				{
					this.OnBarErsaliNamRanandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliNamRanande = value;
					this.SendPropertyChanged("BarErsaliNamRanande");
					this.OnBarErsaliNamRanandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliFamilyRanande", DbType="NVarChar(150)")]
		public string BarErsaliFamilyRanande
		{
			get
			{
				return this._BarErsaliFamilyRanande;
			}
			set
			{
				if ((this._BarErsaliFamilyRanande != value))
				{
					this.OnBarErsaliFamilyRanandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliFamilyRanande = value;
					this.SendPropertyChanged("BarErsaliFamilyRanande");
					this.OnBarErsaliFamilyRanandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliMobileRanande", DbType="VarChar(11)")]
		public string BarErsaliMobileRanande
		{
			get
			{
				return this._BarErsaliMobileRanande;
			}
			set
			{
				if ((this._BarErsaliMobileRanande != value))
				{
					this.OnBarErsaliMobileRanandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliMobileRanande = value;
					this.SendPropertyChanged("BarErsaliMobileRanande");
					this.OnBarErsaliMobileRanandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliKerayeRanande", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BarErsaliKerayeRanande
		{
			get
			{
				return this._BarErsaliKerayeRanande;
			}
			set
			{
				if ((this._BarErsaliKerayeRanande != value))
				{
					this.OnBarErsaliKerayeRanandeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliKerayeRanande = value;
					this.SendPropertyChanged("BarErsaliKerayeRanande");
					this.OnBarErsaliKerayeRanandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliPishKeraye", DbType="Decimal(12,0) NOT NULL")]
		public decimal BarErsaliPishKeraye
		{
			get
			{
				return this._BarErsaliPishKeraye;
			}
			set
			{
				if ((this._BarErsaliPishKeraye != value))
				{
					this.OnBarErsaliPishKerayeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliPishKeraye = value;
					this.SendPropertyChanged("BarErsaliPishKeraye");
					this.OnBarErsaliPishKerayeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliPasKeraye", DbType="Decimal(12,0) NOT NULL")]
		public decimal BarErsaliPasKeraye
		{
			get
			{
				return this._BarErsaliPasKeraye;
			}
			set
			{
				if ((this._BarErsaliPasKeraye != value))
				{
					this.OnBarErsaliPasKerayeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliPasKeraye = value;
					this.SendPropertyChanged("BarErsaliPasKeraye");
					this.OnBarErsaliPasKerayeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliBime", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BarErsaliBime
		{
			get
			{
				return this._BarErsaliBime;
			}
			set
			{
				if ((this._BarErsaliBime != value))
				{
					this.OnBarErsaliBimeChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliBime = value;
					this.SendPropertyChanged("BarErsaliBime");
					this.OnBarErsaliBimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliAnbardari", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BarErsaliAnbardari
		{
			get
			{
				return this._BarErsaliAnbardari;
			}
			set
			{
				if ((this._BarErsaliAnbardari != value))
				{
					this.OnBarErsaliAnbardariChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliAnbardari = value;
					this.SendPropertyChanged("BarErsaliAnbardari");
					this.OnBarErsaliAnbardariChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliShahri", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BarErsaliShahri
		{
			get
			{
				return this._BarErsaliShahri;
			}
			set
			{
				if ((this._BarErsaliShahri != value))
				{
					this.OnBarErsaliShahriChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliShahri = value;
					this.SendPropertyChanged("BarErsaliShahri");
					this.OnBarErsaliShahriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliBastebandi", DbType="Decimal(12,0)")]
		public System.Nullable<decimal> BarErsaliBastebandi
		{
			get
			{
				return this._BarErsaliBastebandi;
			}
			set
			{
				if ((this._BarErsaliBastebandi != value))
				{
					this.OnBarErsaliBastebandiChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliBastebandi = value;
					this.SendPropertyChanged("BarErsaliBastebandi");
					this.OnBarErsaliBastebandiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarErsaliUserNameKarmand", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string BarErsaliUserNameKarmand
		{
			get
			{
				return this._BarErsaliUserNameKarmand;
			}
			set
			{
				if ((this._BarErsaliUserNameKarmand != value))
				{
					if (this._Users_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBarErsaliUserNameKarmandChanging(value);
					this.SendPropertyChanging();
					this._BarErsaliUserNameKarmand = value;
					this.SendPropertyChanged("BarErsaliUserNameKarmand");
					this.OnBarErsaliUserNameKarmandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BarErsali_Tbl_KalaDaryafti_Tbl", Storage="_KalaDaryafti_Tbls", ThisKey="BarErsaliBarname", OtherKey="KalaDaryaftiBarname")]
		public EntitySet<KalaDaryafti_Tbl> KalaDaryafti_Tbls
		{
			get
			{
				return this._KalaDaryafti_Tbls;
			}
			set
			{
				this._KalaDaryafti_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ranande_Tbl_BarErsali_Tbl", Storage="_Ranande_Tbl", ThisKey="BarErsaliCodeRanande", OtherKey="RanandeCodeRanande", IsForeignKey=true, DeleteRule="CASCADE")]
		public Ranande_Tbl Ranande_Tbl
		{
			get
			{
				return this._Ranande_Tbl.Entity;
			}
			set
			{
				Ranande_Tbl previousValue = this._Ranande_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Ranande_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ranande_Tbl.Entity = null;
						previousValue.BarErsali_Tbls.Remove(this);
					}
					this._Ranande_Tbl.Entity = value;
					if ((value != null))
					{
						value.BarErsali_Tbls.Add(this);
						this._BarErsaliCodeRanande = value.RanandeCodeRanande;
					}
					else
					{
						this._BarErsaliCodeRanande = default(string);
					}
					this.SendPropertyChanged("Ranande_Tbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_Tbl_BarErsali_Tbl", Storage="_Users_Tbl", ThisKey="BarErsaliUserNameKarmand", OtherKey="UsersUserName", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Users_Tbl Users_Tbl
		{
			get
			{
				return this._Users_Tbl.Entity;
			}
			set
			{
				Users_Tbl previousValue = this._Users_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Users_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Users_Tbl.Entity = null;
						previousValue.BarErsali_Tbls.Remove(this);
					}
					this._Users_Tbl.Entity = value;
					if ((value != null))
					{
						value.BarErsali_Tbls.Add(this);
						this._BarErsaliUserNameKarmand = value.UsersUserName;
					}
					else
					{
						this._BarErsaliUserNameKarmand = default(string);
					}
					this.SendPropertyChanged("Users_Tbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customers_Tbl_BarErsali_Tbl", Storage="_Customers_Tbl", ThisKey="BarErsaliCodeFerestande", OtherKey="CustomersCode", IsForeignKey=true, DeleteRule="CASCADE")]
		public Customers_Tbl Customers_Tbl
		{
			get
			{
				return this._Customers_Tbl.Entity;
			}
			set
			{
				Customers_Tbl previousValue = this._Customers_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Customers_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Customers_Tbl.Entity = null;
						previousValue.BarErsali_Tbls.Remove(this);
					}
					this._Customers_Tbl.Entity = value;
					if ((value != null))
					{
						value.BarErsali_Tbls.Add(this);
						this._BarErsaliCodeFerestande = value.CustomersCode;
					}
					else
					{
						this._BarErsaliCodeFerestande = default(string);
					}
					this.SendPropertyChanged("Customers_Tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KalaDaryafti_Tbls(KalaDaryafti_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.BarErsali_Tbl = this;
		}
		
		private void detach_KalaDaryafti_Tbls(KalaDaryafti_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.BarErsali_Tbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KalaDaryafti_Tbl")]
	public partial class KalaDaryafti_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KalaDaryaftiCodeKala;
		
		private string _KalaDaryaftiBarname;
		
		private string _KalaDaryaftiNamKala;
		
		private int _KalaDaryaftiTedadKala;
		
		private System.Nullable<decimal> _KalaDaryaftiArzeshKala;
		
		private EntityRef<BarErsali_Tbl> _BarErsali_Tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKalaDaryaftiCodeKalaChanging(string value);
    partial void OnKalaDaryaftiCodeKalaChanged();
    partial void OnKalaDaryaftiBarnameChanging(string value);
    partial void OnKalaDaryaftiBarnameChanged();
    partial void OnKalaDaryaftiNamKalaChanging(string value);
    partial void OnKalaDaryaftiNamKalaChanged();
    partial void OnKalaDaryaftiTedadKalaChanging(int value);
    partial void OnKalaDaryaftiTedadKalaChanged();
    partial void OnKalaDaryaftiArzeshKalaChanging(System.Nullable<decimal> value);
    partial void OnKalaDaryaftiArzeshKalaChanged();
    #endregion
		
		public KalaDaryafti_Tbl()
		{
			this._BarErsali_Tbl = default(EntityRef<BarErsali_Tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KalaDaryaftiCodeKala", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KalaDaryaftiCodeKala
		{
			get
			{
				return this._KalaDaryaftiCodeKala;
			}
			set
			{
				if ((this._KalaDaryaftiCodeKala != value))
				{
					this.OnKalaDaryaftiCodeKalaChanging(value);
					this.SendPropertyChanging();
					this._KalaDaryaftiCodeKala = value;
					this.SendPropertyChanged("KalaDaryaftiCodeKala");
					this.OnKalaDaryaftiCodeKalaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KalaDaryaftiBarname", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KalaDaryaftiBarname
		{
			get
			{
				return this._KalaDaryaftiBarname;
			}
			set
			{
				if ((this._KalaDaryaftiBarname != value))
				{
					if (this._BarErsali_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKalaDaryaftiBarnameChanging(value);
					this.SendPropertyChanging();
					this._KalaDaryaftiBarname = value;
					this.SendPropertyChanged("KalaDaryaftiBarname");
					this.OnKalaDaryaftiBarnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KalaDaryaftiNamKala", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string KalaDaryaftiNamKala
		{
			get
			{
				return this._KalaDaryaftiNamKala;
			}
			set
			{
				if ((this._KalaDaryaftiNamKala != value))
				{
					this.OnKalaDaryaftiNamKalaChanging(value);
					this.SendPropertyChanging();
					this._KalaDaryaftiNamKala = value;
					this.SendPropertyChanged("KalaDaryaftiNamKala");
					this.OnKalaDaryaftiNamKalaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KalaDaryaftiTedadKala", DbType="Int NOT NULL")]
		public int KalaDaryaftiTedadKala
		{
			get
			{
				return this._KalaDaryaftiTedadKala;
			}
			set
			{
				if ((this._KalaDaryaftiTedadKala != value))
				{
					this.OnKalaDaryaftiTedadKalaChanging(value);
					this.SendPropertyChanging();
					this._KalaDaryaftiTedadKala = value;
					this.SendPropertyChanged("KalaDaryaftiTedadKala");
					this.OnKalaDaryaftiTedadKalaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KalaDaryaftiArzeshKala", DbType="Decimal(15,0)")]
		public System.Nullable<decimal> KalaDaryaftiArzeshKala
		{
			get
			{
				return this._KalaDaryaftiArzeshKala;
			}
			set
			{
				if ((this._KalaDaryaftiArzeshKala != value))
				{
					this.OnKalaDaryaftiArzeshKalaChanging(value);
					this.SendPropertyChanging();
					this._KalaDaryaftiArzeshKala = value;
					this.SendPropertyChanged("KalaDaryaftiArzeshKala");
					this.OnKalaDaryaftiArzeshKalaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BarErsali_Tbl_KalaDaryafti_Tbl", Storage="_BarErsali_Tbl", ThisKey="KalaDaryaftiBarname", OtherKey="BarErsaliBarname", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public BarErsali_Tbl BarErsali_Tbl
		{
			get
			{
				return this._BarErsali_Tbl.Entity;
			}
			set
			{
				BarErsali_Tbl previousValue = this._BarErsali_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._BarErsali_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BarErsali_Tbl.Entity = null;
						previousValue.KalaDaryafti_Tbls.Remove(this);
					}
					this._BarErsali_Tbl.Entity = value;
					if ((value != null))
					{
						value.KalaDaryafti_Tbls.Add(this);
						this._KalaDaryaftiBarname = value.BarErsaliBarname;
					}
					else
					{
						this._KalaDaryaftiBarname = default(string);
					}
					this.SendPropertyChanged("BarErsali_Tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ranande_Tbl")]
	public partial class Ranande_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _RanandeCodeRanande;
		
		private string _RanandeFirstName;
		
		private string _RanandeLastName;
		
		private string _RanandeMobile;
		
		private EntitySet<BarErsali_Tbl> _BarErsali_Tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRanandeCodeRanandeChanging(string value);
    partial void OnRanandeCodeRanandeChanged();
    partial void OnRanandeFirstNameChanging(string value);
    partial void OnRanandeFirstNameChanged();
    partial void OnRanandeLastNameChanging(string value);
    partial void OnRanandeLastNameChanged();
    partial void OnRanandeMobileChanging(string value);
    partial void OnRanandeMobileChanged();
    #endregion
		
		public Ranande_Tbl()
		{
			this._BarErsali_Tbls = new EntitySet<BarErsali_Tbl>(new Action<BarErsali_Tbl>(this.attach_BarErsali_Tbls), new Action<BarErsali_Tbl>(this.detach_BarErsali_Tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RanandeCodeRanande", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string RanandeCodeRanande
		{
			get
			{
				return this._RanandeCodeRanande;
			}
			set
			{
				if ((this._RanandeCodeRanande != value))
				{
					this.OnRanandeCodeRanandeChanging(value);
					this.SendPropertyChanging();
					this._RanandeCodeRanande = value;
					this.SendPropertyChanged("RanandeCodeRanande");
					this.OnRanandeCodeRanandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RanandeFirstName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string RanandeFirstName
		{
			get
			{
				return this._RanandeFirstName;
			}
			set
			{
				if ((this._RanandeFirstName != value))
				{
					this.OnRanandeFirstNameChanging(value);
					this.SendPropertyChanging();
					this._RanandeFirstName = value;
					this.SendPropertyChanged("RanandeFirstName");
					this.OnRanandeFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RanandeLastName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string RanandeLastName
		{
			get
			{
				return this._RanandeLastName;
			}
			set
			{
				if ((this._RanandeLastName != value))
				{
					this.OnRanandeLastNameChanging(value);
					this.SendPropertyChanging();
					this._RanandeLastName = value;
					this.SendPropertyChanged("RanandeLastName");
					this.OnRanandeLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RanandeMobile", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string RanandeMobile
		{
			get
			{
				return this._RanandeMobile;
			}
			set
			{
				if ((this._RanandeMobile != value))
				{
					this.OnRanandeMobileChanging(value);
					this.SendPropertyChanging();
					this._RanandeMobile = value;
					this.SendPropertyChanged("RanandeMobile");
					this.OnRanandeMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ranande_Tbl_BarErsali_Tbl", Storage="_BarErsali_Tbls", ThisKey="RanandeCodeRanande", OtherKey="BarErsaliCodeRanande")]
		public EntitySet<BarErsali_Tbl> BarErsali_Tbls
		{
			get
			{
				return this._BarErsali_Tbls;
			}
			set
			{
				this._BarErsali_Tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BarErsali_Tbls(BarErsali_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Ranande_Tbl = this;
		}
		
		private void detach_BarErsali_Tbls(BarErsali_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Ranande_Tbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users_Tbl")]
	public partial class Users_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UsersFirstName;
		
		private string _UsersLastName;
		
		private string _UsersUserName;
		
		private string _UsersPassWord;
		
		private string _UsersMobile;
		
		private bool _UsersDelete;
		
		private bool _UsersRoll;
		
		private EntitySet<BarErsali_Tbl> _BarErsali_Tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsersFirstNameChanging(string value);
    partial void OnUsersFirstNameChanged();
    partial void OnUsersLastNameChanging(string value);
    partial void OnUsersLastNameChanged();
    partial void OnUsersUserNameChanging(string value);
    partial void OnUsersUserNameChanged();
    partial void OnUsersPassWordChanging(string value);
    partial void OnUsersPassWordChanged();
    partial void OnUsersMobileChanging(string value);
    partial void OnUsersMobileChanged();
    partial void OnUsersDeleteChanging(bool value);
    partial void OnUsersDeleteChanged();
    partial void OnUsersRollChanging(bool value);
    partial void OnUsersRollChanged();
    #endregion
		
		public Users_Tbl()
		{
			this._BarErsali_Tbls = new EntitySet<BarErsali_Tbl>(new Action<BarErsali_Tbl>(this.attach_BarErsali_Tbls), new Action<BarErsali_Tbl>(this.detach_BarErsali_Tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersFirstName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UsersFirstName
		{
			get
			{
				return this._UsersFirstName;
			}
			set
			{
				if ((this._UsersFirstName != value))
				{
					this.OnUsersFirstNameChanging(value);
					this.SendPropertyChanging();
					this._UsersFirstName = value;
					this.SendPropertyChanged("UsersFirstName");
					this.OnUsersFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersLastName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string UsersLastName
		{
			get
			{
				return this._UsersLastName;
			}
			set
			{
				if ((this._UsersLastName != value))
				{
					this.OnUsersLastNameChanging(value);
					this.SendPropertyChanging();
					this._UsersLastName = value;
					this.SendPropertyChanged("UsersLastName");
					this.OnUsersLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersUserName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UsersUserName
		{
			get
			{
				return this._UsersUserName;
			}
			set
			{
				if ((this._UsersUserName != value))
				{
					this.OnUsersUserNameChanging(value);
					this.SendPropertyChanging();
					this._UsersUserName = value;
					this.SendPropertyChanged("UsersUserName");
					this.OnUsersUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersPassWord", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UsersPassWord
		{
			get
			{
				return this._UsersPassWord;
			}
			set
			{
				if ((this._UsersPassWord != value))
				{
					this.OnUsersPassWordChanging(value);
					this.SendPropertyChanging();
					this._UsersPassWord = value;
					this.SendPropertyChanged("UsersPassWord");
					this.OnUsersPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersMobile", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string UsersMobile
		{
			get
			{
				return this._UsersMobile;
			}
			set
			{
				if ((this._UsersMobile != value))
				{
					this.OnUsersMobileChanging(value);
					this.SendPropertyChanging();
					this._UsersMobile = value;
					this.SendPropertyChanged("UsersMobile");
					this.OnUsersMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersDelete", DbType="Bit NOT NULL")]
		public bool UsersDelete
		{
			get
			{
				return this._UsersDelete;
			}
			set
			{
				if ((this._UsersDelete != value))
				{
					this.OnUsersDeleteChanging(value);
					this.SendPropertyChanging();
					this._UsersDelete = value;
					this.SendPropertyChanged("UsersDelete");
					this.OnUsersDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsersRoll", DbType="Bit NOT NULL")]
		public bool UsersRoll
		{
			get
			{
				return this._UsersRoll;
			}
			set
			{
				if ((this._UsersRoll != value))
				{
					this.OnUsersRollChanging(value);
					this.SendPropertyChanging();
					this._UsersRoll = value;
					this.SendPropertyChanged("UsersRoll");
					this.OnUsersRollChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Users_Tbl_BarErsali_Tbl", Storage="_BarErsali_Tbls", ThisKey="UsersUserName", OtherKey="BarErsaliUserNameKarmand")]
		public EntitySet<BarErsali_Tbl> BarErsali_Tbls
		{
			get
			{
				return this._BarErsali_Tbls;
			}
			set
			{
				this._BarErsali_Tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BarErsali_Tbls(BarErsali_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Users_Tbl = this;
		}
		
		private void detach_BarErsali_Tbls(BarErsali_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Users_Tbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.City_Tbl")]
	public partial class City_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CityShahr;
		
		private string _CityAnbar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCityShahrChanging(string value);
    partial void OnCityShahrChanged();
    partial void OnCityAnbarChanging(string value);
    partial void OnCityAnbarChanged();
    #endregion
		
		public City_Tbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityShahr", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CityShahr
		{
			get
			{
				return this._CityShahr;
			}
			set
			{
				if ((this._CityShahr != value))
				{
					this.OnCityShahrChanging(value);
					this.SendPropertyChanging();
					this._CityShahr = value;
					this.SendPropertyChanged("CityShahr");
					this.OnCityShahrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CityAnbar", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CityAnbar
		{
			get
			{
				return this._CityAnbar;
			}
			set
			{
				if ((this._CityAnbar != value))
				{
					this.OnCityAnbarChanging(value);
					this.SendPropertyChanging();
					this._CityAnbar = value;
					this.SendPropertyChanged("CityAnbar");
					this.OnCityAnbarChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customers_Tbl")]
	public partial class Customers_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CustomersCode;
		
		private string _CustomersFirstName;
		
		private string _CustomersLastName;
		
		private string _CustomersMobile;
		
		private string _CustomersCity;
		
		private bool _CustomersIsDelete;
		
		private EntitySet<BarErsali_Tbl> _BarErsali_Tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCustomersCodeChanging(string value);
    partial void OnCustomersCodeChanged();
    partial void OnCustomersFirstNameChanging(string value);
    partial void OnCustomersFirstNameChanged();
    partial void OnCustomersLastNameChanging(string value);
    partial void OnCustomersLastNameChanged();
    partial void OnCustomersMobileChanging(string value);
    partial void OnCustomersMobileChanged();
    partial void OnCustomersCityChanging(string value);
    partial void OnCustomersCityChanged();
    partial void OnCustomersIsDeleteChanging(bool value);
    partial void OnCustomersIsDeleteChanged();
    #endregion
		
		public Customers_Tbl()
		{
			this._BarErsali_Tbls = new EntitySet<BarErsali_Tbl>(new Action<BarErsali_Tbl>(this.attach_BarErsali_Tbls), new Action<BarErsali_Tbl>(this.detach_BarErsali_Tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomersCode", DbType="VarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CustomersCode
		{
			get
			{
				return this._CustomersCode;
			}
			set
			{
				if ((this._CustomersCode != value))
				{
					this.OnCustomersCodeChanging(value);
					this.SendPropertyChanging();
					this._CustomersCode = value;
					this.SendPropertyChanged("CustomersCode");
					this.OnCustomersCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomersFirstName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string CustomersFirstName
		{
			get
			{
				return this._CustomersFirstName;
			}
			set
			{
				if ((this._CustomersFirstName != value))
				{
					this.OnCustomersFirstNameChanging(value);
					this.SendPropertyChanging();
					this._CustomersFirstName = value;
					this.SendPropertyChanged("CustomersFirstName");
					this.OnCustomersFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomersLastName", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string CustomersLastName
		{
			get
			{
				return this._CustomersLastName;
			}
			set
			{
				if ((this._CustomersLastName != value))
				{
					this.OnCustomersLastNameChanging(value);
					this.SendPropertyChanging();
					this._CustomersLastName = value;
					this.SendPropertyChanged("CustomersLastName");
					this.OnCustomersLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomersMobile", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string CustomersMobile
		{
			get
			{
				return this._CustomersMobile;
			}
			set
			{
				if ((this._CustomersMobile != value))
				{
					this.OnCustomersMobileChanging(value);
					this.SendPropertyChanging();
					this._CustomersMobile = value;
					this.SendPropertyChanged("CustomersMobile");
					this.OnCustomersMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomersCity", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string CustomersCity
		{
			get
			{
				return this._CustomersCity;
			}
			set
			{
				if ((this._CustomersCity != value))
				{
					this.OnCustomersCityChanging(value);
					this.SendPropertyChanging();
					this._CustomersCity = value;
					this.SendPropertyChanged("CustomersCity");
					this.OnCustomersCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomersIsDelete", DbType="Bit NOT NULL")]
		public bool CustomersIsDelete
		{
			get
			{
				return this._CustomersIsDelete;
			}
			set
			{
				if ((this._CustomersIsDelete != value))
				{
					this.OnCustomersIsDeleteChanging(value);
					this.SendPropertyChanging();
					this._CustomersIsDelete = value;
					this.SendPropertyChanged("CustomersIsDelete");
					this.OnCustomersIsDeleteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Customers_Tbl_BarErsali_Tbl", Storage="_BarErsali_Tbls", ThisKey="CustomersCode", OtherKey="BarErsaliCodeFerestande")]
		public EntitySet<BarErsali_Tbl> BarErsali_Tbls
		{
			get
			{
				return this._BarErsali_Tbls;
			}
			set
			{
				this._BarErsali_Tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BarErsali_Tbls(BarErsali_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Customers_Tbl = this;
		}
		
		private void detach_BarErsali_Tbls(BarErsali_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Customers_Tbl = null;
		}
	}
}
#pragma warning restore 1591
